import { adminDb } from "@/firebase/firebase.admin";
import { firestore } from "firebase-admin";

export type MailPayload = {
  to: string[];
  from?: string;
  message: {
    subject: string;
    text?: string;
    html?: string;
  };
};

export class MailService {
  private static colRef = adminDb.collection("mail");

  static async sendMail(payload: MailPayload) {
    const EMAIL_FROM = process.env.EMAIL_FROM;
    let emailFrom = "Synapse";

    if (payload.from) {
      emailFrom = payload.from;
    } else if (EMAIL_FROM) {
      emailFrom = EMAIL_FROM;
    }

    try {
      const docRef = await this.colRef.add({
        ...payload,
        from: emailFrom,
        createdAt: firestore.FieldValue.serverTimestamp()
      });

      return { id: docRef.id };
    } catch (error) {
      console.error("Failed to send mail:", error);
      throw error;
    }
  }

  static createClientUserWelcomeTemplate({
    firstName,
    passwordLink
  }: {
    firstName: string;
    passwordLink: string;
  }) {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <title>Welcome Email</title>
        </head>
        <body style="font-family: Arial, sans-serif; font-size: 16px; color: #333; line-height: 1.6; margin: 0; padding: 20px; background-color: #f9f9f9;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 900px; margin: auto; background: #ffffff; padding: 30px; border-radius: 8px;">
            <tr>
              <td>
                <p>Hi <strong>${firstName}</strong>,</p>
      
                <p>You’ve been registered on Synapse!</p>

                <p>
                  Your account is ready. Click below to set your password and log in.
                </p>

                <p>
                  👉  <a href="${passwordLink}" style="color: #ffffff; background: #1F3C3C; text-decoration: none; padding: 10px 20px; border-radius: 8px; display: inline-block;">Set Your Password</a>
                </p>

                <p>
                  <strong>Note:</strong> The link expires after one hour. If it’s expired, you’ll be prompted to enter your email and Synapse will automatically send you a new link.
                </p>
              </td>
            </tr>
          </table>
        </body>
      </html>        
      `;
  }

  static createContactUsTemplate({
    description,
    email,
    firstName,
    lastName,
    subject
  }: {
    firstName: string;
    lastName: string;
    email: string;
    subject: string;
    description: string;
  }) {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <title>New Contact Form Submission from Synapse</title>
        </head>
        <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
          <table width="100%" cellspacing="0" cellpadding="0" style="max-width: 600px; margin: auto; background: #ffffff; border: 1px solid #e5e5e5; border-radius: 8px;">
            <tr>
              <td style="padding: 20px; text-align: center; background: #004d40; color: #ffffff; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">Contact Form Submission</h2>
              </td>
            </tr>
            <tr>
              <td style="padding: 20px; color: #333333;">
                <p>You have received a new message from your website contact form:</p>
                <table width="100%" cellspacing="0" cellpadding="6" style="border-collapse: collapse;">
                  <tr>
                    <td style="font-weight: bold; width: 120px;">Name:</td>
                    <td>${firstName} ${lastName}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Email:</td>
                    <td>${email}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Subject:</td>
                    <td>${subject}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold; vertical-align: top;">Description:</td>
                    <td>${description}</td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td style="padding: 15px; text-align: center; font-size: 12px; color: #888888; border-top: 1px solid #e5e5e5;">
                This email was automatically generated by synapse contact form.
              </td>
            </tr>
          </table>
        </body>
      </html>    
    `;
  }
}
