import nodemailer from "nodemailer";

export type MailPayload = {
  to: string[];
  from?: string;
  message: {
    subject: string;
    text?: string;
    html?: string;
  };
};

export class MailService {
  private static getTransporter() {
    return nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      },
      tls: {
        rejectUnauthorized: false
      }
    });
  }

  static async sendMail(payload: MailPayload) {
    const transporter = this.getTransporter();
    const EMAIL_FROM = process.env.EMAIL_FROM || "Synapse";
    const emailFrom = payload.from || EMAIL_FROM;

    try {
      const info = await transporter.sendMail({
        from: `"${emailFrom}" <${process.env.SMTP_USER}>`,
        to: payload.to.join(", "),
        subject: payload.message.subject,
        text: payload.message.text,
        html: payload.message.html
      });

      console.log("Email sent: %s", info.messageId);
      return { id: info.messageId };
    } catch (error) {
      console.error("Failed to send mail via Nodemailer:", error);
      throw error;
    }
  }

  static createClientUserWelcomeTemplate({
    firstName,
    passwordLink
  }: {
    firstName: string;
    passwordLink: string;
  }) {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <title>Welcome Email</title>
        </head>
        <body style="font-family: Arial, sans-serif; font-size: 16px; color: #333; line-height: 1.6; margin: 0; padding: 20px; background-color: #f9f9f9;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 900px; margin: auto; background: #ffffff; padding: 30px; border-radius: 8px;">
            <tr>
              <td>
                <p>Hi <strong>${firstName}</strong>,</p>
      
                <p>You’ve been registered on Synapse!</p>

                <p>
                  Your account is ready. Click below to set your password and log in.
                </p>

                <p>
                  👉  <a href="${passwordLink}" style="color: #ffffff; background: #1F3C3C; text-decoration: none; padding: 10px 20px; border-radius: 8px; display: inline-block;">Set Your Password</a>
                </p>

                <p>
                  <strong>Note:</strong> The link expires after one hour. If it’s expired, you’ll be prompted to enter your email and Synapse will automatically send you a new link.
                </p>
              </td>
            </tr>
          </table>
        </body>
      </html>        
      `;
  }

  static createContactUsTemplate({
    description,
    email,
    firstName,
    lastName,
    subject
  }: {
    firstName: string;
    lastName: string;
    email: string;
    subject: string;
    description: string;
  }) {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <title>New Contact Form Submission from Synapse</title>
        </head>
        <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
          <table width="100%" cellspacing="0" cellpadding="0" style="max-width: 600px; margin: auto; background: #ffffff; border: 1px solid #e5e5e5; border-radius: 8px;">
            <tr>
              <td style="padding: 20px; text-align: center; background: #004d40; color: #ffffff; border-radius: 8px 8px 0 0;">
                <h2 style="margin: 0;">Contact Form Submission</h2>
              </td>
            </tr>
            <tr>
              <td style="padding: 20px; color: #333333;">
                <p>You have received a new message from your website contact form:</p>
                <table width="100%" cellspacing="0" cellpadding="6" style="border-collapse: collapse;">
                  <tr>
                    <td style="font-weight: bold; width: 120px;">Name:</td>
                    <td>${firstName} ${lastName}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Email:</td>
                    <td>${email}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Subject:</td>
                    <td>${subject}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold; vertical-align: top;">Description:</td>
                    <td>${description}</td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td style="padding: 15px; text-align: center; font-size: 12px; color: #888888; border-top: 1px solid #e5e5e5;">
                This email was automatically generated by synapse contact form.
              </td>
            </tr>
          </table>
        </body>
      </html>    
    `;
  }

  static createResetPasswordTemplate({
    firstName,
    resetLink
  }: {
    firstName: string;
    resetLink: string;
  }) {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <title>Reset Your Password</title>
        </head>
        <body style="font-family: Arial, sans-serif; font-size: 16px; color: #333; line-height: 1.6; margin: 0; padding: 20px; background-color: #f9f9f9;">
          <table width="100%" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; margin: auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #e5e5e5;">
            <tr>
              <td>
                <h2 style="color: #173dba; margin-top: 0;">Reset Your Password</h2>
                <p>Hi <strong>${firstName}</strong>,</p>
      
                <p>We received a request to reset the password for your Synapse account. No changes have been made yet.</p>

                <p>You can reset your password by clicking the button below:</p>

                <p style="text-align: center; padding: 20px 0;">
                  <a href="${resetLink}" style="color: #ffffff; background: #173dba; text-decoration: none; padding: 12px 25px; border-radius: 8px; display: inline-block; font-weight: bold;">Reset Password</a>
                </p>

                <p>For security reasons, this link will expire in 1 hour. If you didn't request a password reset, you can safely ignore this email.</p>
                
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
                
                <p style="font-size: 12px; color: #888;">
                  If you're having trouble clicking the button, copy and paste the URL below into your web browser:
                  <br />
                  <span style="word-break: break-all; color: #1F3C3C;">${resetLink}</span>
                </p>
              </td>
            </tr>
          </table>
        </body>
      </html>        
      `;
  }
}
